# Copyright 2023 the Limbo authors. All rights reserved. MIT license.

[workspace]
resolver = "2"
members = [
  "bindings/wasm",
  "cli",
  "sqlite3",
  "core",
  "simulator",
]
exclude = ["perf/latency/limbo"]

[workspace.package]
version = "0.0.3"
authors = ["the Limbo authors"]
edition = "2021"
license = "MIT"
repository = "https://github.com/penberg/limbo"

[workspace.metadata.dist]
cargo-dist-version = "0.19.1"
ci = "github"
installers = ["shell"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
pr-run-mode = "plan"
install-path = "~/.limbo/"
install-updater = true
dist = false

[profile.dist]
inherits = "release"
lto = "thin"
