# Copyright 2023 the Limbo authors. All rights reserved. MIT license.

[workspace]
resolver = "2"
members = [
  "bindings/wasm",
  "cli",
  "core",
]

[workspace.package]
authors = ["the Limbo authors"]
edition = "2021"
license = "MIT"
repository = "https://github.com/penberg/limbo"
