# Copyright 2023 the Limbo authors. All rights reserved. MIT license.

[package]
name = "limbo_core"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "The Limbo database library"

[lib]
name = "limbo_core"
path = "lib.rs"

[features]
default = ["fs"]
fs = []

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.6.1"

[dependencies]
anyhow = "1.0.75"
cfg_block = "0.1.1"
concurrent_lru = "0.2.0"
fallible-iterator = "0.3.0"
log = "0.4.20"
mimalloc = { version = "*", default-features = false }
sqlite3-parser = "0.11.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async", "async_futures"] }
pprof = { version = "0.12.1", features = ["criterion", "flamegraph"] }
rstest = "0.18.2"
rusqlite = "0.29.0"

[[bench]]
name = "benchmark"
harness = false
